name = str(input ("Enter your name: "))
print ("Hello " + name  + ". Have a good day!")
user = str(input ("How can I assist you:"))
print ("I'm good!, thanks for asking")
user = str(input ("What are you doing: "))
print ("Same here,just chillin'then?:")
user = str(input ("Let me know if you wanna talk or share something!:"))
print ("Thank's for the chat")
user = str(input ("bye:"))
print ("Catch ya later!")